---

- name: Ensure scripts directory exists
  file: path={{ scriptsdir }} state=directory mode=0755

- name: add backup script
  template: src=backup-jira.sh.j2 dest={{ scriptsdir }}/backup-jira.sh mode=0755
- name: add restore script
  template: src=restore-jira.sh.j2 dest={{ scriptsdir }}/restore-jira.sh mode=0755

- name: apt | ensure cron is installed
  apt: name=cron state=present
  when: ansible_os_family == 'Debian'
  register: pkg_result
  until: pkg_result is success

- name: yum | ensure cron is installed
  yum: name=crontabs state=present
  when: ansible_os_family == "RedHat"
  register: pkg_result
  until: pkg_result is success

- name: setup cron backup
  cron: name="jira-backup" minute="3" hour="23" weekday="0"
    job="{{ scriptsdir }}/backup-jira.sh > /dev/null 2>&1"
    user=root
    cron_file=ansible_jira-backup
