---
## https://confluence.atlassian.com/jira/connecting-jira-to-postgresql-185729433.html
## https://confluence.atlassian.com/jira/supported-platforms-207488170.html     Officially up to 9.3

- name: Configure postgresql backend with template
  template:
    src: dbconfig.xml.j2
    dest: "{{ jira_homedir }}/dbconfig.xml"
    mode: '0400'
    owner: jira
    backup: yes
  register: p1
  notify:
    - restart jira

- include: restore.yml
  when: jira_db_restorefile is defined and jira_db_restorefile|string
