---

- name: Ensure python-lxml is present
  package:
    name: python-lxml
    state: present

## FIXME! want to have Connector 8443 but keep Connector 8080
##  "Can't process Xpath ./@port=8443 in order to spawn nodes! tree is <Connector/>\n"
- name: Jira https | Update tomcat configuration
  xml:
    path: /opt/atlassian/jira/current/conf/server.xml
    xpath: "/Server/Service/Connector[@port=8443]"
    state: present
    attribute: "{{ item.attr }}"
    value: "{{ item.val }}"
    # backup: yes
  with_items:
    - { attr: 'protocol', val: 'org.apache.coyote.http11.Http11NioProtocol' }
    - { attr: 'maxHttpHeaderSize', val: '8192' }
    - { attr: 'SSLEnabled', val: 'true' }
    - { attr: 'scheme', val: 'https' }
    - { attr: 'secure', val: 'true' }
    - { attr: 'clientAuth', val: 'false' }
    - { attr: 'sslProtocol', val: 'TLS' }
    - { attr: 'keystoreFile', val: "{{ jira_keystore }}" }
    - { attr: 'keystorePass', val: "{{ jira_keystore_pass }}" }
    - { attr: 'keystoreType', val: 'JKS' }
    - { attr: 'maxThreads', val: '150' }
    - { attr: 'minSpareThreads', val: '25' }
    - { attr: 'enableLookups', val: 'false' }
    - { attr: 'disableUploadTimeout', val: 'true' }
    - { attr: 'acceptCount', val: '100' }

- name: Jira https | Update tomcat configuration
  xml:
    path: /opt/atlassian/jira/current/conf/server.xml
    xpath: "/Server/Service/Connector[@port=8080]"
    state: present
    attribute: "{{ item.attr }}"
    value: "{{ item.val }}"
    # backup: yes
  with_items:
    - { attr: 'redirectPort', val: '8443' }
