---

- name: Upload certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ jira_homedir }}/{{ item | basename }}"
    mode: '0644'
    backup: yes
  with_items: "{{ jira_keystore_cert_import }}"

- name: Import Certificate into jira keystore  # noqa no-changed-when
  ansible.builtin.command: >
    keytool -importcert -keystore ./jre/lib/security/cacerts
        -file "{{ jira_homedir }}/{{ item | basename }}"
        -storepass "{{ jira_keystore_storepass | default('changeit') }}" -noprompt
  with_items: "{{ jira_keystore_cert_import }}"
