---

- name: Configure Jira server.xml
  ansible.builtin.template:
    src: server.xml.j2
    dest: "{{ jira_installdir }}/conf/server.xml"
    mode: '0644'
    owner: jira
    group: jira
    backup: yes
