---

- name: Ensure python-lxml is present
  ansible.builtin.package:
    name: python-lxml
    state: present

- name: Check if have a jira server.xml backup
  ansible.builtin.stat:
    path: "{{ jira_installdir }}/conf/server.xml.orig"
  register: backup
- name: Backup jira server.xml
  ansible.builtin.copy:
    src: "{{ jira_installdir }}/conf/server.xml"
    dest: "{{ jira_installdir }}/conf/server.xml.orig"
    mode: '0400'
    remote_src: true
  when: not backup.stat.exists

- name: Reverse Proxy | Update jira context path
  community.general.xml:
    path: "{{ jira_installdir }}/conf/server.xml"
    xpath: /Server/Service/Engine/Host/Context
    state: present
    attribute: path
    value: "{{ jira_context_path | default('/') }}"
    # backup: yes
  notify:
    - Restart jira
