---
## https://confluence.atlassian.com/kb/proxying-atlassian-server-applications-with-apache-http-server-mod_proxy_http-806032611.html
## https://confluence.atlassian.com/adminjiraserver071/integrating-jira-with-apache-using-ssl-802593043.html

#- include: jira-server_xml1.yml
- include: jira-server_xml2.yml

- name: setup jira reverse-proxy configuration
  template:
    src: apache-jira.conf.j2
    dest: "{{ apache_sitedir }}/jira-vhost.conf"
    mode: '0644'
    backup: yes
  notify:
    - restart apache
- name: Debian | enable jira configuration
  file:
    src: "{{ apache_sitedir }}/jira-vhost.conf"
    dest: "/etc/apache2/sites-enabled/jira-vhost.conf"
    state: link
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
    - debug: var=ansible_selinux
    - name: RedHat7- | ensure selinux dependency is present
      yum:
        name:
          - libselinux-python
          - libsemanage-python
        state: present
      register: pkg_result
      until: pkg_result is success
      when: ansible_distribution_major_version|int < 8

    - name: RedHat8+ | Ensure selinux dependencies are present
      package:
        name:
          - python3-libselinux
          - python3-libsemanage
        state: present
      register: pkg_result
      until: pkg_result is success
      when: ansible_distribution_major_version|int >= 8

    - name: RedHat | Allow apache to connect to network (selinux)
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
  when: >
    ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7 and
    ansible_selinux.status is defined and
    ansible_selinux.status != 'disabled'

#- name: Disable HTTP compression in Jira - GUI only???
