---

- name: Ensure logging tools are present
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rsyslog
    - logrotate

- name: get rsyslog version
  command: "rsyslogd -v | awk -F'[ ,]' '/rsyslogd/ { print $2 }'"
  changed_when: false
  register: rsyslog_v

- name: ensure /etc/rsyslog.d exists
  file: dest=/etc/rsyslog.d state=directory mode=0755

- name: send ufw log to separate file through rsyslog
  template: src=rsyslog-ufw.conf.j2 dest=/etc/rsyslog.d/49-ufw.conf mode=0644
  notify:
    - restart rsyslog

- name: ensure /etc/logrotate.d exists
  file: dest=/etc/logrotate.d state=directory mode=0755

- name: add logrotate configuration for ufw.log
  template: src=logrotate-ufw.j2 dest=/etc/logrotate.d/ufw mode=0644

