---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == "Debian"
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: Import jira-java11-fix
  ansible.builtin.import_tasks: jira-java11-fix.yml
  when:
    - jira_version|string is version_compare('8.20.0', '>=')
    - (ansible_os_family == "Debian" and ansible_distribution_major_version|int >= 18) or
      (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)

- name: Import backup-restore
  ansible.builtin.import_tasks: backup-restore.yml

- name: Import security
  ansible.builtin.import_tasks: security.yml

- name: Import jira-postgresql
  ansible.builtin.import_tasks: jira-postgresql.yml
  when: jira_dbbackend is defined and jira_dbbackend == 'postgres'

# - ansible.builtin.import_tasks: jira-server_xml1.yml
- name: Import jira-server_xml2
  ansible.builtin.import_tasks: jira-server_xml2.yml

- name: Import jira-reverseproxy
  ansible.builtin.import_tasks: jira-reverseproxy.yml
  when: jira_reverseproxy|bool

- name: Import jira-https
  ansible.builtin.import_tasks: jira-https.yml
  when: jira_https|bool

- name: Import jira-import-crt
  ansible.builtin.import_tasks: jira-import-crt.yml

- name: Import jira-activedirectory
  ansible.builtin.import_tasks: jira-activedirectory.yml
  when: jira_link_activedirectory|bool

- name: Install curl for serverspec testing
  ansible.builtin.package:
    name: curl
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Jira has finished to initialize
  ansible.builtin.wait_for:
    port: "{{ jira_int_port }}"
    delay: 15
  register: w1
  ignore_errors: true

- name: Restart 2
  when: w1 is failed
  block:
    - name: 2nd jira restart
      ansible.builtin.service:
        name: jira
        state: restarted
    - name: Ensure Jira has finished to initialize 2
      ansible.builtin.wait_for:
        port: "{{ jira_int_port }}"
        delay: 15
