---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == "Debian"
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- include: backup-restore.yml

- include: security.yml

- include: jira-postgresql.yml
  when: jira_dbbackend is defined and jira_dbbackend == 'postgres'

- include: jira-reverseproxy.yml
  when: jira_reverseproxy|bool

- include: jira-https.yml
  when: jira_https|bool

- include: jira-import-crt.yml

- include: jira-activedirectory.yml
  when: jira_link_activedirectory|bool

- name: install curl for serverspec testing
  package: name=curl state=present
  register: pkg_result
  until: pkg_result is success

- meta: flush_handlers

- name: Ensure Jira has finished to initialize
  wait_for:
    port: "{{ jira_int_port }}"
    delay: 15
  register: w1
  ignore_errors: true

- block:
    - name: 2nd jira restart
      service:
        name: jira
        state: restarted
    - name: Ensure Jira has finished to initialize 2
      wait_for:
        port: "{{ jira_int_port }}"
        delay: 15
  when: w1 is failed
