---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == "Debian"
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- include: backup-restore.yml

- include: security.yml

- include: jira-postgresql.yml
  when: jira_dbbackend is defined and jira_dbbackend == 'postgres'

- include: jira-reverseproxy.yml
  when: jira_reverseproxy

- include: jira-https.yml
  when: jira_https

- include: jira-activedirectory.yml
  when: jira_link_activedirectory

- name: install curl for serverspec testing
  package: name=curl state=present
