---
## https://confluence.atlassian.com/adminjiraserver071/server-optimization-802593159.html

- name: Restrict some path with robots.txt
  template:
    src: robots.txt.j2
    dest: "{{ jira_installdir }}/robots.txt"
    mode: '0644'
    backup: yes

## https://confluence.atlassian.com/adminjiraserver071/logging-and-profiling-802592962.html

## https://confluence.atlassian.com/adminjiraserver071/using-apache-to-limit-access-to-the-jira-administration-interface-802593047.html

## https://confluence.atlassian.com/adminjiraserver071/configuring-security-in-the-external-environment-802593075.html

- import_tasks: firewall-ufw.yml
  when: not (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker"))
