---

- name: Restart jira
  ansible.builtin.service: name=jira state=restarted

- name: Restart apache
  ansible.builtin.service: name={{ apache_svc }} state=restarted
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: Restart rsyslog
  ansible.builtin.service: name=rsyslog state=restarted
