# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/jammy64"
    #config.vm.box = "generic/centos9s"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "vagrantselect" => ["vjira" ],
       }
    end

    config.vm.define "vjira" do |vjira|
        vjira.vm.hostname = "vjira"
        vjira.vm.provider "virtualbox" do |v|
          v.memory = 1024
        end
        vjira.vm.network "forwarded_port", guest: 80, host: 8080
        vjira.vm.network "forwarded_port", guest: 443, host: 8043
    end

end
